---
title: "cleaning"
format: html
---

## SETUP Chunk
```{r setup}
#include: false
source(here::here("R/functions.R"))
library(tidyverse)
```

```{r}
hr_data <- read_all("HR.csv.gz") |>
  get_participant_id() |>
  summarise_by_datetime()

ibi_data <- read_all("IBI.csv.gz") |>
  get_participant_id() |>
  summarise_by_datetime()

temp_data <- read_all("TEMP.csv.gz") |>
  get_participant_id() |>
  summarise_by_datetime()

bvp_data <- read_all("BVP.csv.gz") |>
  get_participant_id() |>
  summarise_by_datetime()

eda_data <- read_all("EDA.csv.gz") |>
  get_participant_id() |>
  summarise_by_datetime()

```


## Process survey data (21.5 Add survey processing to docs/cleaning.qmd)
```{r}
survey_tidy <- here::here("data-raw/nurses-stress/survey-results.csv.gz") |>
  read() |>
  tidy_survey_dates()

survey_long <- survey_tidy |>
  survey_to_long()
```

## Full join data

```{r}
nurses_stress <- survey_long |>
  full_join(survey_tidy) |> 
  full_join(hr_data)

nurses_stress |> 
  arrange(id, collection_datetime) |> 
  View()
```

## Full join remaining data

```{r}
nurses_stress <- survey_long |>
  full_join(survey_tidy) |>
  full_join(hr_data) |>
  full_join(ibi_data) |>
  full_join(temp_data) |>
  full_join(bvp_data) |>
  full_join(eda_data)
```

