---
title: "learning"
author: "ML"
format: html
---
## SETUP Chunk
```{r setup}
library(tidyverse)
library(here)
library(snakecase)
library(fs)
source(here("R/functions.R"))
```

##Importing new data
```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

## Exercise: Reading other files

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case, ,
    n_max = 100
  )
```
## Exercise: Reading other files, case 2

```{r}
here("data-raw/nurses-stress/stress/6B/6B_1587569373/EDA.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
  )
```
## Exercise: Limit rows

```{r}
here("data-raw/nurses-stress/stress/6B/6B_1587569373/EDA.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = "unique",
    n_max = 100
  )
```

## Exercise: Create function

```{r}
#' Add two number together
#'
#' @param One number
#' @param Another number here
#'
#' @returns returns the sum of two numbers
add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}
```

## Exercise: create functions, continued

```{r}
#' Read in one nurses stress data file
#'
#' @param file_path path to a data file
#'
#' @returns outputs table with max 100 columns

read <- function(file_path) {
  data <- file_path |>
    read_csv(
      show_col_types = FALSE,
      name_repair = to_snake_case,
      n_max = 100
    )
  return(data)
}
```

## Exercise: final function

```{r}
#' Test function
#'
#' @param file_path
#' @param max_rows
#'
#' @returns your taxes, fiscal year 1987

read <- function(file_path, max_rows = 100) {
  data <- file_path |>
    readr::read_csv(
      show_col_types = FALSE,
      name_repair = to_snake_case,
      n_max = max_rows
    )
  return(data)
}

here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read()

here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(max_rows = 1000)

here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(max_rows = Inf)
```

##Uisng map

```{r}
hr_files <- here("data-raw/nurses-stress/") |>
  dir_ls(regexp = "HR.csv.gz", recurse = TRUE)

hr_files

hr_data <- hr_files |>
  map(read) |>
  list_rbind(names_to = "file_path_id")

hr_data
```
